name: mango_secure
version: 1.0.0
description: Wrapper for Secure API
repository: https://github.com/louisevanderlith/secure
homepage: https://github.com/louisevanderlith/secure
environment:
  sdk: '>=2.0.0 < 3.0.0'
dependencies:
  mango_ui: '^1.0.1'